[package]
name = "namedarg"
version = "0.1.0"
authors = ["comex <comexk@gmail.com>"]

[dependencies]

[lib]
crate-type = ["rlib", "dylib"]

[features]
derive_debug = []
println_spam = ["derive_debug"]
use_rlex = []
