[package]
name = "namedarg_rustc_macro"
version = "0.1.0"
authors = ["comex <comexk@gmail.com>"]

[lib]
rustc-macro = true

[dependencies]

[features]
default = ["use_rlex", "rustc_macro_mode"]
derive_debug = []
println_spam = ["derive_debug"]
use_rlex = []
rustc_macro_mode = []
