[package]
name = "namedarg_plugin"
version = "0.1.0"
authors = ["comex <comexk@gmail.com>"]

[lib]
crate_type = ["dylib"]

[dependencies]

[features]
derive_debug = []
println_spam = ["derive_debug"]
use_rlex = []
